
version: '3'
services:
  app:
    container_name: server
    restart: always
    volumes:
      - ".:/var/www/myapp"
    build: .
    ports: 
      - "${API_PORT}:${API_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"

    links:
      - redis
      - mongo
  mongo:
    container_name: mongoDB
    image: 'mongo:4.0.11'
    command: mongod --port ${MONGODB_PORT}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
  redis:
    container_name: redis
    image: 'redis:5.0.5'
    command: redis-server --port ${REDIS_PORT}
    ports: 
      - "${REDIS_PORT}:${REDIS_PORT}"